modify installer scripts
common: if no stow -> echo error msg & exit with error
    install-maestral: if no virtualenv -> echo error msg & exit with error
    install-cli: zsh refresh on previous(called on) pwd

diff --git a/scripts/install-cli b/scripts/install-cli
--- a/scripts/install-cli
+++ b/scripts/install-cli
@@ -1,8 +1,14 @@
 #!/usr/bin/env sh
 readonly XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
 
+err_nostow () {
+    echo "ERROR: There is no stow" >&2
+    exit 1
+}
+
 install () {
     # cd to cli directory
+    local BACKUP_PATH=$(pwd)
     cd $(realpath $(dirname $0))
     cd $(git rev-parse --show-cdup)/cli
 
@@ -21,10 +27,11 @@ install () {
     git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
 
     # reload zsh for install zinit (zsh)
-    exec zsh
+    exec zsh $BACKUP_PATH
 }
 
-[ -x $(which stow) ] && install || stow
+[ -x $(which stow) ] || err_nostow
+install
 
 # vim:ft=sh
 # vim:wrap!
diff --git a/scripts/install-maestral b/scripts/install-maestral
--- a/scripts/install-maestral
+++ b/scripts/install-maestral
@@ -2,6 +2,16 @@
 readonly XDG_DATA_HOME=${XDG_DATA_HOME:-"${HOME}/.local/share"}
 readonly MAESTRAL_VENV=${XDG_DATA_HOME}/maestral_venv
 
+err_nostow () {
+    echo "ERROR: There is no stow" >&2
+    exit 1
+}
+
+err_novirtualenv () {
+    echo "ERROR: There is no virtualenv" >&2
+    exit 1
+}
+
 stow_maestral () {
     # cd to cli directory
     cd $(realpath $(dirname $0))
@@ -30,8 +40,8 @@ install_maestral () {
     exit 0
 }
 
-[ -x $(which stow) ] || stow
-[ -x $(which virtualenv) ] || virtualenv
+[ -x $(which stow) ] || err_nostow
+[ -x $(which virtualenv) ] || err_novirtualenv
 
 stow_maestral
 install_maestral
